name: Deploy feature branches to nonproduction bucket

on:
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo 'Hello World'
